/** AUTOGENERATED - DO NOT EDIT **/
/* tslint:disable */
/* eslint-disable */

import { z } from "zod/v4"

export const s_HealthCheckResponse = z.object({
  version: z.string(),
  uptime: z.coerce.number(),
})
